    name: Build textbook
    
    on:
      push:
        branches:
          - master
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository content
            uses: actions/checkout@v2
          - name: Setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.9
          - name: Install requirements
            run: |
              pip install -r requirements.txt
          - name: Build textbook
            run: |
              python script/main.py
            env:
              GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
          - name: Update Google token
          uses: hmanzur/actions-set-secret@v2.0.0
          with:
            name: 'GOOGLE_TOKEN_JSON'
            value: ${{ GOOGLE_TOKEN_JSON }}
            repository: vishnupsatish/textbook-data-management
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
          - name: Commit to repository
            run: |
              git config --global user.name 'Vishnu Satish'
              git config --global user.email 'vishnupsatish@users.noreply.github.com'
              git add .
              git commit -m "Automated textbook build"
              git push origin master
